# Project garage-door-controller
# Description: MQTT client for my garage door
# Author: Jason Learst <jason.learst@gmail.com>
# Date: 2022-01-22
#
# Garage Door Controller
# Copyright (C) 2022 Jason Learst
# 
# This program incorporates a modified version of Garage Door Opener MQTT
# Copyright (C) 2020  MrDIY
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

cover:
  - platform: mqtt
    name: "garage"
    device_class: garage
    state_topic: "garage-cover/door/status"
    command_topic: "garage-cover/door/action"
    availability_topic: "garage-cover/availability"